name: Basic Checks

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        make init
    - name: Check our style
      run: |
        make style
    - name: Pre release
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        make pre-release
        git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master --tags
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_TEST_PASSWORD }}
