name: PR Pipeline
run-name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install poetry
        run: pipx install poetry

      - name: Run tests
        run: |
          poetry env use python3.12
          poetry install
          poetry run flake8
          poetry run pytest
