name: PR Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        make init
    - name: Check our style
      run: |
        make tests
    - name: Publish documentation
      run: |
        make doc-devel
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
